### ISSUE TITLE
Improve documentation on dependencies with Advanced Logic in Config

### ISSUE THREAD

**Issue by BigsonLvrocha** [labs42io/circleci-monorepo#17]
Advanced logic in Config is a thing now in circleci, so, it should be documented, it wwould be a solution without change the script

the announcement is [here](https://discuss.circleci.com/t/advanced-logic-in-config/36011)

So, given 2 packages, `api` and `service` that depends on `common`, the script should be ok with 
```yml
workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows


  # Workflows defined for each package.

  api:
    when: 
      or: 
        - << pipeline.parameters.api >>
        - << pipeline.parameters.common >>
    jobs:
      - build:
          name: api-build
          package_name: api
      - deploy:
          name: api-deploy
          package_name: api
          requires:
            - api-build

service:
    when: 
      or: 
        - << pipeline.parameters.service >>
        - << pipeline.parameters.common >>
    jobs:
      - build:
          name: service-build
          package_name: service
      - deploy:
          name: service-deploy
          package_name: service
          requires:
            - service-build
```
